# Generated by Django 3.2 on 2023-05-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fin_prdt_cd',
            new_name='deposit_fin_prdt_nm',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fin_prdt_cd_saving',
            new_name='saving_fin_prdt_nm',
        ),
    ]
