# Generated by Django 3.2 on 2023-05-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230523_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deposit_fin_prdt_nm',
            new_name='fin_prdt_cd',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='saving_fin_prdt_nm',
            new_name='fin_prdt_cd_saving',
        ),
    ]
